import type { TeamMember, BoardMember, Project, Post, MediaItem } from '@/types/database';

export const colors = {
  primary: {
    DEFAULT: '#0092DF',
    hover: '#007DC2',
    50: '#E6F4FC',
    100: '#CCEAFA',
    500: '#0092DF',
    600: '#007DC2',
    700: '#005A8D',
    900: '#003D60',
  },
  secondary: {
    DEFAULT: '#86C127',
    hover: '#6EA71F',
    50: '#F3F9E9',
    100: '#E7F4D4',
  },
  accent: {
    DEFAULT: '#E67817',
    hover: '#CF660F',
    50: '#FDF2E8',
  },
  text: {
    primary: '#1E293B',
    secondary: '#64748B',
    muted: '#94A3B8',
  },
  bg: {
    white: '#FFFFFF',
    soft: '#F7FAF8',
    section: '#F3F7F5',
  },
  border: '#E2E8F0',
} as const;

export const programmeColors = {
  'adolescent-and-youth-health-and-development': {
    accent: '#0092DF',
    bg: '#E6F4FC',
    border: '#B3E0F7',
    text: '#005A8D',
  },
  'maternal-newborn-and-child-health': {
    accent: '#0092DF',
    bg: '#E6F4FC',
    border: '#B3E0F7',
    text: '#005A8D',
  },
  'gender-based-violence-prevention-and-response': {
    accent: '#86C127',
    bg: '#F3F9E9',
    border: '#D2EBB0',
    text: '#4A7512',
  },
  'peacebuilding-and-social-cohesion': {
    accent: '#86C127',
    bg: '#F3F9E9',
    border: '#D2EBB0',
    text: '#4A7512',
  },
  'community-engagement-and-social-accountability': {
    accent: '#86C127',
    bg: '#F3F9E9',
    border: '#D2EBB0',
    text: '#4A7512',
  },
  'digital-innovation-and-data-for-development': {
    accent: '#E67817',
    bg: '#FDF2E8',
    border: '#FCD8B8',
    text: '#9C4E0B',
  },
} as const;

export const thematicFocusAreas = [
  {
    id: 'public-health',
    slug: 'public-health',
    title: 'Public Health',
    accentColor: '#0092DF',
    description:
      'Strengthening primary healthcare, adolescent & maternal health, health promotion, nutrition, and disease prevention across communities.',
  },
  {
    id: 'education-and-youth',
    slug: 'education-and-youth',
    title: 'Youth Empowerment & Education',
    accentColor: '#E67817',
    description:
      'Vocational development, digital skills, leadership training, and economic empowerment initiatives for adolescent girls and youth.',
  },
  {
    id: 'good-governance',
    slug: 'good-governance',
    title: 'Civic Engagement & Accountability',
    accentColor: '#86C127',
    description:
      'Community scorecards, youth-led budget monitoring, social accountability tracking, and institutional advocacy.',
  },
  {
    id: 'peacebuilding',
    slug: 'peacebuilding',
    title: 'Peacebuilding & Social Cohesion',
    accentColor: '#86C127',
    description:
      'Fostering communal dialogue, youth mediation, early warning systems, and inter-faith conflict transformation.',
  },
  {
    id: 'climate-resilience',
    slug: 'climate-resilience',
    title: 'Climate Resilience & Health',
    accentColor: '#E67817',
    description:
      'Addressing the impact of environmental degradation on community health, food security, and rural livelihoods.',
  },
] as const;

export const flagshipInitiatives = [
  {
    id: 'skills-hub',
    title: 'e-CAPH Skills Hub',
    category: 'Economic Empowerment',
    accentColor: '#86C127',
    description:
      'High-demand digital technology, entrepreneurship, and vocational skills for women and youth economic independence.',
    location: 'Kaduna & Kano',
    isFeatured: true,
  },
  {
    id: 'gani-da-ido',
    title: 'Gani da Ido',
    category: 'Civic Accountability',
    accentColor: '#0092DF',
    description:
      'Youth-led social accountability project monitoring primary healthcare services, budgets, and public service delivery.',
    location: 'Northern Nigeria',
    isFeatured: true,
  },
] as const;

export const technicalApproaches = [
  {
    number: '01',
    title: 'Gender and Human Rights',
    description:
      'Ensuring every programme is rights-based, gender-responsive, inclusive, and strictly aligned with safeguarding principles.',
  },
  {
    number: '02',
    title: 'Community Participation',
    description:
      'Designing and implementing interventions side-by-side with communities rather than imposing solutions from above.',
  },
  {
    number: '03',
    title: 'Evidence, Research and Learning',
    description:
      'Utilizing empirical data, field research, and continuous learning to inform programme design and policy advocacy.',
  },
  {
    number: '04',
    title: 'Innovation',
    description:
      'Applying modern technology, digital tools, and creative methodologies to maximize community engagement and impact.',
  },
  {
    number: '05',
    title: 'Strategic Partnerships',
    description:
      'Collaborating with local governments, civil society, international agencies, and community leaders to scale impact sustainably.',
  },
] as const;

export const officialTeamMembers: TeamMember[] = [
  {
    id: 'team-1',
    full_name: 'Dr. Fatima Abubakar',
    role_title: 'Executive Director & Founder',
    bio: 'Public health physician with 15+ years leading health systems reform and community interventions in Nigeria.',
    avatar_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80',
    email: 'fatima@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'team-2',
    full_name: 'Ibrahim Sani',
    role_title: 'Director of Programmes',
    bio: 'Development strategist overseeing adolescent health, civic accountability, and youth economic empowerment initiatives.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    email: 'ibrahim@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'team-3',
    full_name: 'Amina Kabir',
    role_title: 'Head of Public Health & ANC',
    bio: 'Epidemiologist leading maternal-newborn health tracking and primary health center community advocacy.',
    avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
    email: 'amina@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'team-4',
    full_name: 'Yusuf Mohammed',
    role_title: 'Lead, Gani da Ido & Governance',
    bio: 'Social accountability expert coordinating Youth Accountability Champions and community service scorecards.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    email: 'yusuf@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const officialBoardMembers: BoardMember[] = [
  {
    id: 'board-1',
    full_name: 'Dr. Hauwa Mustapha',
    board_role: 'Chairman, Board of Trustees',
    bio: 'Renowned public health strategist and governance advisor.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    email: 'info@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'board-2',
    full_name: 'Barr. Usman Danjuma',
    board_role: 'Board Trustee & Legal Counsel',
    bio: 'Human rights lawyer and legal reform advocate.',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    email: 'info@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'board-3',
    full_name: 'Hajia Maryam Bello',
    board_role: 'Board Trustee & Financial Steward',
    bio: 'Development finance specialist and women rights advocate.',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    email: 'info@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'board-4',
    full_name: 'Prof. Kabir Ahmed',
    board_role: 'Senior Technical Advisor',
    bio: 'Professor of Community Medicine and Health Policy.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    email: 'info@e-caph.org',
    linkedin_url: null,
    twitter_url: null,
    order_index: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const officialProjects: Project[] = [
  {
    id: 'init-skills-hub',
    programme_id: null,
    title: 'e-CAPH Skills Hub',
    slug: 'ecaph-skills-hub-women-youth-empowerment',
    summary: 'An economic empowerment initiative designed to equip women and young people with practical vocational and entrepreneurial skills that improve economic opportunities while addressing social vulnerabilities.',
    description: `The e-CAPH Skills Hub for women and youth empowerment is an economic empowerment initiative designed to equip women and young people with practical vocational and entrepreneurial skills that improve their economic opportunities while also addressing social vulnerabilities.\n\nThrough the Hub, Participants acquire high-demand skills in digital technology, entrepreneurship, vocational development, leadership, employability, and other emerging areas. Our goal is not only to provide training, but also to strengthen confidence, creativity, economic independence, and the ability of participants to contribute meaningfully to their communities.`,
    objectives: ['Equip women and youth with high-demand digital technology, entrepreneurship, and vocational development skills.'],
    activities: ['Vocational workshops', 'Digital literacy bootcamps', 'Business startup mentoring', 'Leadership circles'],
    results_to_date: ['Over 250 young women and youth trained across local communities.'],
    target_beneficiaries: 'Women, adolescent girls, and unemployed youth.',
    location: 'Kaduna & Kano, Nigeria',
    donor_partner: 'e-CAPH Community Development Fund',
    status: 'ongoing',
    start_date: '2025-01-15',
    end_date: null,
    featured_image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    is_flagship: true,
    is_published: true,
    budget: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'init-gani-da-ido',
    programme_id: null,
    title: 'Gani da Ido - Muryar Matasa – Idon Al’umma',
    slug: 'gani-da-ido-youth-civic-accountability',
    summary: 'A youth-led civic engagement and social accountability project that amplifies young people’s voices and strengthens community participation in public decision-making.',
    description: `The e-CAPH Gani da Ido - Muryar Matasa – Idon Al’umma is a youth-led civic engagement and social accountability project that amplifies young people’s voices and strengthens community participation in public decision-making.\n\nThe project enables citizens to monitor public services, budgets, government commitments and development projects through accessible digital and community-based platforms. It provides safe channels for submitting complaints, sharing feedback and tracking how responsible institutions respond. Through Youth Accountability Champions, community scorecards, public dialogues and evidence-based advocacy, the project promotes transparency, inclusion and improved service delivery.`,
    objectives: ['Promote public service transparency, community scorecards, and youth-led budget monitoring.'],
    activities: ['Youth Accountability Champions training', 'Primary healthcare facility scorecards', 'Public Town Hall dialogues'],
    results_to_date: ['Monitored over 40 primary healthcare centers and trained 120 Youth Accountability Champions.'],
    target_beneficiaries: 'Youth advocates, local ward citizens, and primary health service users.',
    location: 'Northern Nigeria Wards',
    donor_partner: 'Civic Governance & Social Accountability Fund',
    status: 'ongoing',
    start_date: '2024-06-01',
    end_date: null,
    featured_image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    is_flagship: true,
    is_published: true,
    budget: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-lafiyar-iyali',
    programme_id: null,
    title: 'Lafiyar Iyali Initiative (Maternal & ANC Tracking)',
    slug: 'lafiyar-iyali-maternal-anc-tracking',
    summary: 'Digital antenatal care tracking system connecting pregnant women with primary healthcare centers for 4th-visit attendance and newborn care.',
    description: `Lafiyar Iyali Initiative is an evidence-informed public health intervention aimed at reducing maternal and neonatal mortality in primary health centers across rural wards in Northern Nigeria.\n\nUsing mobile digital tracking tools and trained Community Health Extension Workers (CHEWs), the initiative tracks pregnant women through 4th-visit antenatal care (ANC), essential immunization schedules, and emergency referral pathways.`,
    objectives: ['Increase 4th-visit antenatal care compliance', 'Strengthen primary health center drug supply tracking'],
    activities: ['CHEW home visits', 'Digital ANC SMS reminders', 'Community health dialogues'],
    results_to_date: ['Over 12,000 pregnant women tracked across 40 primary health centers.'],
    target_beneficiaries: 'Pregnant women, mothers, and newborns in rural communities.',
    location: 'Kaduna, Kano & Katsina Wards',
    donor_partner: 'Public Health Action Alliance',
    status: 'ongoing',
    start_date: '2023-09-01',
    end_date: null,
    featured_image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
    is_flagship: true,
    is_published: true,
    budget: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const officialPosts: Post[] = [
  {
    id: 'post-1',
    author_id: null,
    category_id: null,
    programme_id: null,
    project_id: null,
    title: 'e-CAPH Launches Skills Hub for Women and Youth Economic Empowerment',
    slug: 'ecaph-launches-skills-hub-women-youth-empowerment',
    summary: 'Equipping young people and women with high-demand vocational skills, digital technology training, and startup support.',
    content: 'The e-CAPH Skills Hub equips participants with practical vocational and entrepreneurial skills to foster economic independence.',
    featured_image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    post_type: 'article',
    status: 'published',
    published_at: new Date().toISOString(),
    views_count: 142,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-2',
    author_id: null,
    category_id: null,
    programme_id: null,
    project_id: null,
    title: 'Gani da Ido: Youth Accountability Champions Tracking Primary Healthcare Services',
    slug: 'gani-da-ido-youth-accountability-champions-primary-healthcare',
    summary: 'Empowering young leaders to monitor community health centers, budget allocations, and public service delivery.',
    content: 'Youth Accountability Champions collect community scorecards across primary health centers in northern Nigeria.',
    featured_image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    post_type: 'report',
    status: 'published',
    published_at: new Date().toISOString(),
    views_count: 98,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-3',
    author_id: null,
    category_id: null,
    programme_id: null,
    project_id: null,
    title: 'Digital ANC Tracking: Enhancing Maternal and Child Survival Rates',
    slug: 'digital-anc-tracking-maternal-child-survival',
    summary: 'How mobile technology and community health workers are improving 4th-visit antenatal attendance in rural wards.',
    content: 'Our digital antenatal care tracking tool connects pregnant women with local primary health centers.',
    featured_image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
    post_type: 'impact_story',
    status: 'published',
    published_at: new Date().toISOString(),
    views_count: 210,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const officialMediaItems: MediaItem[] = [
  {
    id: 'media-1',
    title: 'Community Health Advocates Training Workshop in Kaduna',
    caption: 'Over 50 grassroots health champions completed our primary healthcare monitoring toolkit training.',
    media_type: 'photo',
    url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    thumbnail_url: null,
    category: 'Community Health',
    order_index: 1,
    is_published: true,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'media-2',
    title: 'Gani da Ido Project Launch & Youth Dialogue',
    caption: 'Official video coverage of the youth-led social accountability town hall meeting.',
    media_type: 'video',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    category: 'Social Accountability',
    order_index: 2,
    is_published: true,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'media-3',
    title: 'Press Statement: Call for Accelerated Implementation of Primary Healthcare Reforms',
    caption: 'e-CAPH issues official press statement advocating transparent budget allocation for maternal-newborn health centers.',
    media_type: 'press_release',
    url: 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf',
    thumbnail_url: null,
    category: 'Policy & Advocacy',
    order_index: 3,
    is_published: true,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
